default_stages: [pre-commit]
default_install_hook_types: [pre-commit, commit-msg]
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-merge-conflict
      - id: check-case-conflict
      - id: check-json
      - id: check-toml
      - id: check-yaml
      - id: pretty-format-json
        args:
          [--autofix, --no-sort-keys, "--top-keys=_id,name,type,description"]
      - id: trailing-whitespace
        exclude: ^.*\.(lock)$||^docs\/
      - id: end-of-file-fixer
        exclude: ^.*\.(lock)$||^docs\/
      - id: mixed-line-ending
        exclude: ^.*\.(lock)$||^docs\/
      - id: detect-private-key
      - id: no-commit-to-branch
        args: [--branch, main]
        stages: [commit-msg]

  - repo: https://github.com/compilerla/conventional-pre-commit
    rev: v2.3.0
    hooks:
      - id: conventional-pre-commit
        stages: [commit-msg]

  - repo: https://github.com/biomejs/pre-commit
    rev: "v0.6.1"
    hooks:
      - id: biome-check
        additional_dependencies: ["@biomejs/biome@1.9.0"]
        files: ^docs/.*\.[jt]sx?$
