repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v2.5.0
  hooks:
    - id: check-merge-conflict
    - id: check-case-conflict
    - id: check-json
    - id: check-yaml
    - id: detect-private-key

- repo: https://github.com/pre-commit/mirrors-prettier
  rev: v2.2.1
  hooks:
    - id: prettier
      files: ^docs/.*\.(ts|tsx|js|css|html|json)$
      args: ['--config=docs/.prettierrc.js', '--ignore-path=docs/.prettierignore']

- repo: local
  hooks:
    - id: eslint
      name: ESlint
      entry: sh -c "cd docs; npm run lint:fix"
      language: system
      pass_filenames: false
