name: On push to main branch

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  run-tests:
    uses: ./.github/workflows/tests.yml

  deploy-docs:
    needs: run-tests
    runs-on: ubuntu-latest
    name: Build and deploy docs to Github pages
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Yarn
        run: npm install -g yarn

      - name: Generate typedocs
        run: |
          cd docs
          yarn install
          yarn run generate-typedocs

      - name: Generate plugin docs
        run: |
          cd docs
          git clone --depth 1 git@github.com:equinor/dm-core-packages.git
          mv dm-core-packages/packages/dm-core-plugins/docs ./plugin-docs
          mkdir --parents ./docs/libraries/@development-framework/dm-core-plugins/
          cp -R ./plugin-docs/* ./docs/libraries/@development-framework/dm-core-plugins/
          mv dm-core-packages/packages/dm-core-plugins/blueprints ./plugin-blueprints
          python3 copy_config.py

      - name: Build docs
        run: |
          cd docs
          yarn install
          yarn run build

      - name: Deploy docs to github pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: docs/build
